In [1]:
import pandas as pd
import json

In [2]:
import snscrape.modules.twitter as sntwitter

# get user
user_catatanali07 = sntwitter.TwitterUserScraper("catatanali07").entity
user_bungs = sntwitter.TwitterUserScraper("__bungs").entity

user1_data = [user_catatanali07.id, user_catatanali07.username, user_catatanali07.location,
              user_catatanali07.followersCount, user_catatanali07.friendsCount, user_catatanali07.favouritesCount,
              user_catatanali07.statusesCount]
user2_data = [user_bungs.id, user_bungs.username, user_bungs.location,
              user_bungs.followersCount, user_bungs.friendsCount, user_bungs.favouritesCount,
              user_bungs.statusesCount]

display(user1_data)
display(user2_data)

['1492190828499902466', 'CatatanAli07', '', 2697, 1559, 226, 4473]

['914271535', '__Bungs', 'Indonesia', 3788, 1449, 459936, 105430]

# CatatanAli07

## Raw Data

In [3]:
tweet = pd.read_csv("tweet_catatanali07_base.csv")
users = pd.read_csv("users_catatanali07_base.csv")
display(tweet)
display(users)

,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,https://twitter.com/CatatanAli07/status/158653...,2022-10-30 01:55:44+00:00,Teruslah Membusuk ü•≥ü•≥ https://t.co/x22eypVSlw,Teruslah Membusuk ü•≥ü•≥ https://t.co/x22eypVSlw,1586537305249939457,"{'username': 'CatatanAli07', 'id': 14921908284...",0,1,0,0,...,[{'previewUrl': 'https://pbs.twimg.com/media/F...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://twitter.com/CatatanAli07/status/158340...,2022-10-21 10:12:06+00:00,Kok seperti ini cara mempromosikan ANIES üò´\n\n...,Kok seperti ini cara mempromosikan ANIES üò´\n\n...,1583400727778852867,"{'username': 'CatatanAli07', 'id': 14921908284...",0,1,1,0,...,NaN,NaN,{'url': 'https://twitter.com/sobat_anies/statu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://twitter.com/CatatanAli07/status/157670...,2022-10-02 22:51:41+00:00,KONTOL !!! https://t.co/2JMHIW05Sj,KONTOL !!! twitter.com/henrysubiakto/‚Ä¶,1576706514840326144,"{'username': 'CatatanAli07', 'id': 14921908284...",0,3,2,0,...,NaN,NaN,{'url': 'https://twitter.com/henrysubiakto/sta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://twitter.com/CatatanAli07/status/157436...,2022-09-26 11:50:26+00:00,Jika PEMERINTAH ingin memberantas PERJUDIAN be...,Jika PEMERINTAH ingin memberantas PERJUDIAN be...,1574365780224794624,"{'username': 'CatatanAli07', 'id': 14921908284...",5,3,5,0,...,NaN,NaN,{'url': 'https://twitter.com/Indostransfer/sta...,NaN,NaN,"[{'username': 'CCICPolri', 'id': 7353583441065...",NaN,NaN,NaN,NaN
4,https://twitter.com/CatatanAli07/status/154682...,2022-07-12 11:55:40+00:00,Mulai nakal ko bodatü§£üòÇ https://t.co/1iOWaPV1bF,Mulai nakal ko bodatü§£üòÇ twitter.com/TheEagle_BE...,1546825616338857985,"{'username': 'CatatanAli07', 'id': 14921908284...",3,0,2,0,...,NaN,NaN,{'url': 'https://twitter.com/TheEagle_BEN/stat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,https://twitter.com/CatatanAli07/status/149267...,2022-02-13 01:34:37+00:00,Mantap neh buat temen ngupi Yok diorder üëç http...,Mantap neh buat temen ngupi Yok diorder üëç twit...,1492673532463304705,"{'username': 'CatatanAli07', 'id': 14921908284...",1,3,4,0,...,NaN,NaN,{'url': 'https://twitter.com/Queen__Bakery/sta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,https://twitter.com/CatatanAli07/status/149246...,2022-02-12 11:51:36+00:00,Keep calm yah masih dibatasi buat polbeküôè,Keep calm yah masih dibatasi buat polbeküôè,1492466412656676866,"{'username': 'CatatanAli07', 'id': 14921908284...",0,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,https://twitter.com/CatatanAli07/status/149241...,2022-02-12 08:42:46+00:00,Gak bosen KO hidup lu kerjaan nya NAKUT NAKUTI...,Gak bosen KO hidup lu kerjaan nya NAKUT NAKUTI...,1492418892924583936,"{'username': 'CatatanAli07', 'id': 14921908284...",1,1,3,0,...,NaN,NaN,{'url': 'https://twitter.com/dr_koko28/status/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,https://twitter.com/CatatanAli07/status/149235...,2022-02-12 04:17:42+00:00,JILAT TERUS \n\nISENG ISENG BERHADIAH YA DIE üòÇ...,JILAT TERUS \n\nISENG ISENG BERHADIAH YA DIE üòÇ...,1492352188148219908,"{'username': 'CatatanAli07', 'id': 14921908284...",0,1,1,0,...,NaN,NaN,{'url': 'https://twitter.com/addiems/status/14...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,https://twitter.com/CatatanAli07/status/149231...,2022-02-12 01:31:24+00:00,#FotoProfilBaru https://t.co/2nj1RH1qRV,#FotoProfilBaru https://t.co/2nj1RH1qRV,1492310337122889729,"{'username': 'CatatanAli07', 'id': 14921908284...",0,0,0,0,...,[{'previewUrl': 'https://pbs.twimg.com/media/F...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['FotoProfilBaru'],NaN

,Id,Username,Followers,Following,Tweets,Likes,Location
0,1492190828499902466,CatatanAli07,2697,1558,4430,224,NaN

In [4]:
tweet_filtered = tweet.filter(items=["id", "date", "url", "content", "likeCount", "replyCount", "retweetCount", "retweetedTweet"])
tweet_filtered = tweet_filtered.assign(user_id=user1_data[0], user_name=user1_data[1], user_location=user1_data[2], 
                      follower_count=user1_data[3], following_count=user1_data[4], likes_count=user1_data[5], tweets_count=user1_data[6])
tweet_filtered = tweet_filtered.rename(columns={
                                        tweet_filtered.columns[0]: "Id", 
                                        tweet_filtered.columns[1]: "Tweet Time", 
                                        tweet_filtered.columns[2]: "Url", 
                                        tweet_filtered.columns[3]: "Tweet Text", 
                                        tweet_filtered.columns[4]: "Likes Count", 
                                        tweet_filtered.columns[5]: "Reply Count", 
                                        tweet_filtered.columns[6]: "Retweet Count", 
                                        tweet_filtered.columns[7]: "Retweeted Tweet", 
                                        tweet_filtered.columns[8]: "User Id", 
                                        tweet_filtered.columns[9]: "User Name", 
                                        tweet_filtered.columns[10]: "User Location", 
                                        tweet_filtered.columns[11]: "User Follower Count", 
                                        tweet_filtered.columns[12]: "User Following Count", 
                                        tweet_filtered.columns[13]: "User Likes Count", 
                                        tweet_filtered.columns[14]: "User Tweets Count", 
                                    })

display(tweet_filtered)

,Id,Tweet Time,Url,Tweet Text,Likes Count,Reply Count,Retweet Count,Retweeted Tweet,User Id,User Name,User Location,User Follower Count,User Following Count,User Likes Count,User Tweets Count
0,1586537305249939457,2022-10-30 01:55:44+00:00,https://twitter.com/CatatanAli07/status/158653...,Teruslah Membusuk ü•≥ü•≥ https://t.co/x22eypVSlw,0,0,1,NaN,1492190828499902466,CatatanAli07,,2697,1559,226,4473
1,1583400727778852867,2022-10-21 10:12:06+00:00,https://twitter.com/CatatanAli07/status/158340...,Kok seperti ini cara mempromosikan ANIES üò´\n\n...,1,0,1,NaN,1492190828499902466,CatatanAli07,,2697,1559,226,4473
2,1576706514840326144,2022-10-02 22:51:41+00:00,https://twitter.com/CatatanAli07/status/157670...,KONTOL !!! https://t.co/2JMHIW05Sj,2,0,3,NaN,1492190828499902466,CatatanAli07,,2697,1559,226,4473
3,1574365780224794624,2022-09-26 11:50:26+00:00,https://twitter.com/CatatanAli07/status/157436...,Jika PEMERINTAH ingin memberantas PERJUDIAN be...,5,5,3,NaN,1492190828499902466,CatatanAli07,,2697,1559,226,4473
4,1546825616338857985,2022-07-12 11:55:40+00:00,https://twitter.com/CatatanAli07/status/154682...,Mulai nakal ko bodatü§£üòÇ https://t.co/1iOWaPV1bF,2,3,0,NaN,1492190828499902466,CatatanAli07,,2697,1559,226,4473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,1492673532463304705,2022-02-13 01:34:37+00:00,https://twitter.com/CatatanAli07/status/149267...,Mantap neh buat temen ngupi Yok diorder üëç http...,4,1,3,NaN,1492190828499902466,CatatanAli07,,2697,1559,226,4473
179,1492466412656676866,2022-02-12 11:51:36+00:00,https://twitter.com/CatatanAli07/status/149246...,Keep calm yah masih dibatasi buat polbeküôè,0,0,1,NaN,1492190828499902466,CatatanAli07,,2697,1559,226,4473
180,1492418892924583936,2022-02-12 08:42:46+00:00,https://twitter.com/CatatanAli07/status/149241...,Gak bosen KO hidup lu kerjaan nya NAKUT NAKUTI...,3,1,1,NaN,1492190828499902466,CatatanAli07,,2697,1559,226,4473
181,1492352188148219908,2022-02-12 04:17:42+00:00,https://twitter.com/CatatanAli07/status/149235...,JILAT TERUS \n\nISENG ISENG BERHADIAH YA DIE üòÇ...,1,0,1,NaN,1492190828499902466,CatatanAli07,,2697,1559,226,4473
182,1492310337122889729,2022-02-12 01:31:24+00:00,https://twitter.com/CatatanAli07/status/149231...,#FotoProfilBaru https://t.co/2nj1RH1qRV,0,0,0,NaN,1492190828499902466,CatatanAli07,,2697,1559,226,4473

In [5]:
base_data = tweet_filtered
base_data.to_csv('merge_catatanali07_base.csv', index=False)

## Replies Data

In [6]:
tweet = pd.read_csv("tweet_catatanali07_replies.csv")
users = pd.read_csv("users_catatanali07_replies.csv")
display(tweet)
display(users)

,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,https://twitter.com/_together___/status/158804...,2022-11-03 06:04:42+00:00,@CatatanAli07 üòÑ,@CatatanAli07 üòÑ,1588049511984771072,"{'username': '_together___', 'id': 13551608969...",0,0,0,0,...,NaN,NaN,NaN,1.588049e+18,"{'username': 'CatatanAli07', 'id': 14921908284...","[{'username': 'CatatanAli07', 'id': 1492190828...",NaN,NaN,NaN,NaN
1,https://twitter.com/TheEagle_BEN/status/157436...,2022-09-26 11:58:09+00:00,@CatatanAli07 JUMPA KAKAK YG DI VIDIO ITU‚ò∫Ô∏è,@CatatanAli07 JUMPA KAKAK YG DI VIDIO ITU‚ò∫Ô∏è,1574367721659461632,"{'username': 'TheEagle_BEN', 'id': 12445258847...",1,0,0,0,...,NaN,NaN,NaN,1.574367e+18,"{'username': 'CatatanAli07', 'id': 14921908284...","[{'username': 'CatatanAli07', 'id': 1492190828...",NaN,NaN,NaN,NaN
2,https://twitter.com/TheEagle_BEN/status/157436...,2022-09-26 11:56:37+00:00,@CatatanAli07 JUDI = JUMPA DICIUMü§£,@CatatanAli07 JUDI = JUMPA DICIUMü§£,1574367333086531584,"{'username': 'TheEagle_BEN', 'id': 12445258847...",1,0,0,0,...,NaN,NaN,NaN,1.574366e+18,"{'username': 'CatatanAli07', 'id': 14921908284...","[{'username': 'CatatanAli07', 'id': 1492190828...",NaN,NaN,NaN,NaN
3,https://twitter.com/CatatanAli07/status/157436...,2022-09-26 11:52:59+00:00,@TheEagle_BEN berhentilah ko main judi bodoh!,@TheEagle_BEN berhentilah ko main judi bodoh!,1574366418279092224,"{'username': 'CatatanAli07', 'id': 14921908284...",1,0,0,0,...,NaN,NaN,NaN,1.574366e+18,"{'username': 'CatatanAli07', 'id': 14921908284...","[{'username': 'TheEagle_BEN', 'id': 1244525884...",NaN,NaN,NaN,NaN
4,https://twitter.com/ad3ira29/status/1571337089...,2022-09-18 03:15:30+00:00,@CatatanAli07 Haha gpplah gw salah mention ya ...,@CatatanAli07 Haha gpplah gw salah mention ya ...,1571337089408733186,"{'username': 'ad3ira29', 'id': 321603383, 'dis...",0,0,0,0,...,NaN,NaN,NaN,1.571336e+18,"{'username': 'CatatanAli07', 'id': 14921908284...","[{'username': 'CatatanAli07', 'id': 1492190828...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1021,https://twitter.com/ArgentianaA/status/1492523...,2022-02-12 15:38:43+00:00,@CatatanAli07 Mirip Ali si Hope perutnya üòÇ,@CatatanAli07 Mirip Ali si Hope perutnya üòÇ,1492523570010144769,"{'username': 'ArgentianaA', 'id': 113303274784...",1,0,0,0,...,NaN,NaN,NaN,1.492521e+18,"{'username': 'CatatanAli07', 'id': 14921908284...","[{'username': 'CatatanAli07', 'id': 1492190828...",NaN,NaN,NaN,NaN
1022,https://twitter.com/GnW_1_kuli/status/14924368...,2022-02-12 09:54:07+00:00,@CatatanAli07 ? https://t.co/ZZ8Oe8CpAO,@CatatanAli07 ? https://t.co/ZZ8Oe8CpAO,1492436849348202499,"{'username': 'GnW_1_kuli', 'id': 1224286263399...",0,0,0,0,...,[{'previewUrl': 'https://pbs.twimg.com/media/F...,NaN,NaN,1.492419e+18,"{'username': 'CatatanAli07', 'id': 14921908284...","[{'username': 'CatatanAli07', 'id': 1492190828...",NaN,NaN,NaN,NaN
1023,https://twitter.com/ArgentianaA/status/1492380...,2022-02-12 06:09:15+00:00,@CatatanAli07 Ali banget itu üòÜ,@CatatanAli07 Ali banget itu üòÜ,1492380257420455937,"{'username': 'ArgentianaA', 'id': 113303274784...",1,0,0,0,...,NaN,NaN,NaN,1.492380e+18,"{'username': 'CatatanAli07', 'id': 14921908284...","[{'username': 'CatatanAli07', 'id': 1492190828...",NaN,NaN,NaN,NaN
1024,https://twitter.com/didihadid_/status/14923462...,2022-02-12 03:54:15+00:00,@CatatanAli07 Eh Sapri,@CatatanAli07 Eh Sapri,1492346287034757120,"{'username': 'didihadid_', 'id': 1175456641543...",1,0,0,0,...,NaN,NaN,NaN,1.492324e+18,"{'username': 'CatatanAli07', 'id': 14921908284...","[{'username': 'CatatanAli07', 'id': 1492190828...",NaN,NaN,NaN,NaN
1025,https://twitter.com/RheinaHerlina/status/14923...,2022-02-12 02:42:35+00:00,@CatatanAli07 Rasü§∏‚Äç‚ôÄÔ∏èü§∏‚Äç‚ôÄÔ∏è,@CatatanAli07 Rasü§∏‚Äç‚ôÄÔ∏èü§∏‚Äç‚ôÄÔ∏è,1492328251255308290,"{'username': 'RheinaHerlina', 'id': 293624229,...",1,0,0,0,...,NaN,NaN,NaN,1.492328e+18,"{'username': 'CatatanAli07', 'id': 14921908284...","[{'username': 'CatatanAli07', 'id': 1492190828...",NaN,NaN,NaN,NaN

,Id,Username,Followers,Following,Tweets,Likes,Location
0,1355160896947937285,_together___,4546,4384,34305,70127,Negeri Bertuhan
1,1561360311784861698,rakpirink,715,751,312,1895,NaN
2,3310598915,Muchsin_Dwi,827,942,31395,17565,Kota Bandung
3,1569121195324489728,ZayLani03036841,17,107,399,154,NaN
4,1466651308102877187,papa_loren,21884,5312,52489,212278,~#
...,...,...,...,...,...,...,...
957,1313317215408586752,WongTan_,3130,2105,13385,4104,NaN
958,1355416500157333505,Queen__Bakery,8883,3728,63700,56025,NaN
959,79739365,Moh_Jupri,1858,2133,29677,9740,Indonesia
960,1224286263399743489,GnW_1_kuli,4901,4664,33786,36757,NaN
961,353739058,Paiminoise,79,94,1893,9,NaN

In [7]:
tweet_filtered = tweet.filter(items=["id", "date", "url", "content", "likeCount", "replyCount", "retweetCount", "retweetedTweet"])

username_series = tweet.user.str.split("', '")
username_series = username_series.apply(lambda x: x[0].split("': '")[1])
tweet_filtered = tweet_filtered.assign(username_user=username_series)

tweet_filtered = tweet_filtered.merge(users, left_on="username_user", right_on="Username", how="left")
# tweet_filtered = tweet_filtered.assign(user_id=user1_data[0], user_name=user1_data[1], user_location=user1_data[2], 
#                       follower_count=user1_data[3], following_count=user1_data[4], likes_count=user1_data[5], tweets_count=user1_data[6])
tweet_filtered = tweet_filtered.drop('username_user', axis=1)
tweet_filtered = tweet_filtered.rename(columns={
                                        tweet_filtered.columns[0]: "Id", 
                                        tweet_filtered.columns[1]: "Tweet Time", 
                                        tweet_filtered.columns[2]: "Url", 
                                        tweet_filtered.columns[3]: "Tweet Text", 
                                        tweet_filtered.columns[4]: "Likes Count", 
                                        tweet_filtered.columns[5]: "Reply Count", 
                                        tweet_filtered.columns[6]: "Retweet Count", 
                                        tweet_filtered.columns[7]: "Retweeted Tweet", 
                                        tweet_filtered.columns[8]: "User Id", 
                                        tweet_filtered.columns[9]: "User Name", 
                                        tweet_filtered.columns[10]: "User Follower Count", 
                                        tweet_filtered.columns[11]: "User Following Count", 
                                        tweet_filtered.columns[12]: "User Tweets Count", 
                                        tweet_filtered.columns[13]: "User Likes Count", 
                                        tweet_filtered.columns[14]: "User Location", 
                                    })

display(tweet_filtered)

,Id,Tweet Time,Url,Tweet Text,Likes Count,Reply Count,Retweet Count,Retweeted Tweet,User Id,User Name,User Follower Count,User Following Count,User Tweets Count,User Likes Count,User Location
0,1588049511984771072,2022-11-03 06:04:42+00:00,https://twitter.com/_together___/status/158804...,@CatatanAli07 üòÑ,0,0,0,NaN,1.355161e+18,_together___,4546.0,4384.0,34305.0,70127.0,Negeri Bertuhan
1,1574367721659461632,2022-09-26 11:58:09+00:00,https://twitter.com/TheEagle_BEN/status/157436...,@CatatanAli07 JUMPA KAKAK YG DI VIDIO ITU‚ò∫Ô∏è,0,1,0,NaN,1.244526e+18,TheEagle_BEN,8503.0,104.0,27414.0,45177.0,NaN
2,1574367333086531584,2022-09-26 11:56:37+00:00,https://twitter.com/TheEagle_BEN/status/157436...,@CatatanAli07 JUDI = JUMPA DICIUMü§£,0,1,0,NaN,1.244526e+18,TheEagle_BEN,8503.0,104.0,27414.0,45177.0,NaN
3,1574366418279092224,2022-09-26 11:52:59+00:00,https://twitter.com/CatatanAli07/status/157436...,@TheEagle_BEN berhentilah ko main judi bodoh!,0,1,0,NaN,1.492191e+18,CatatanAli07,2698.0,1558.0,4430.0,224.0,NaN
4,1571337089408733186,2022-09-18 03:15:30+00:00,https://twitter.com/ad3ira29/status/1571337089...,@CatatanAli07 Haha gpplah gw salah mention ya ...,0,0,0,NaN,3.216034e+08,ad3ira29,19869.0,6977.0,67425.0,148916.0,Jakarta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1021,1492523570010144769,2022-02-12 15:38:43+00:00,https://twitter.com/ArgentianaA/status/1492523...,@CatatanAli07 Mirip Ali si Hope perutnya üòÇ,0,1,0,NaN,1.133033e+18,ArgentianaA,15501.0,2602.0,291584.0,5488.0,Behind you
1022,1492436849348202499,2022-02-12 09:54:07+00:00,https://twitter.com/GnW_1_kuli/status/14924368...,@CatatanAli07 ? https://t.co/ZZ8Oe8CpAO,0,0,0,NaN,1.224286e+18,GnW_1_kuli,4901.0,4664.0,33786.0,36757.0,NaN
1023,1492380257420455937,2022-02-12 06:09:15+00:00,https://twitter.com/ArgentianaA/status/1492380...,@CatatanAli07 Ali banget itu üòÜ,0,1,0,NaN,1.133033e+18,ArgentianaA,15501.0,2602.0,291584.0,5488.0,Behind you
1024,1492346287034757120,2022-02-12 03:54:15+00:00,https://twitter.com/didihadid_/status/14923462...,@CatatanAli07 Eh Sapri,0,1,0,NaN,1.175457e+18,didihadid_,3050.0,1704.0,159285.0,37228.0,üé™üé†üé¢üé°‚õ≤üèñÔ∏èüèùÔ∏è
1025,1492328251255308290,2022-02-12 02:42:35+00:00,https://twitter.com/RheinaHerlina/status/14923...,@CatatanAli07 Rasü§∏‚Äç‚ôÄÔ∏èü§∏‚Äç‚ôÄÔ∏è,0,1,0,NaN,2.936242e+08,RheinaHerlina,34060.0,12813.0,61084.0,121022.0,dihatimu

In [8]:
replies_data = tweet_filtered
replies_data.to_csv('merge_catatanali07_replies.csv', index=False)

## Retweet Data

In [9]:
# Skip karna 0
# tweet = pd.read_csv("tweet_catatanali07_retweets.csv")
# users = pd.read_csv("users_catatanali07_retweets.csv")
# display(tweet)
# display(users)

In [10]:
# tweet_filtered = tweet.filter(items=["id", "date", "url", "content", "likeCount", "replyCount", "retweetCount", "retweetedTweet"])

# username_series = tweet.user.str.split("', '")
# username_series = username_series.apply(lambda x: x[0].split("': '")[1])
# tweet_filtered = tweet_filtered.assign(username_user=username_series)

# tweet_filtered = tweet_filtered.merge(users, left_on="username_user", right_on="Username", how="left")
# # tweet_filtered = tweet_filtered.assign(user_id=user1_data[0], user_name=user1_data[1], user_location=user1_data[2], 
# #                       follower_count=user1_data[3], following_count=user1_data[4], likes_count=user1_data[5], tweets_count=user1_data[6])
# tweet_filtered = tweet_filtered.rename(columns={
#                                         tweet_filtered.columns[0]: "Id", 
#                                         tweet_filtered.columns[1]: "Tweet Time", 
#                                         tweet_filtered.columns[2]: "Url", 
#                                         tweet_filtered.columns[3]: "Tweet Text", 
#                                         tweet_filtered.columns[4]: "Likes Count", 
#                                         tweet_filtered.columns[5]: "Reply Count", 
#                                         tweet_filtered.columns[6]: "Retweet Count", 
#                                         tweet_filtered.columns[7]: "Retweeted Tweet", 
#                                         tweet_filtered.columns[8]: "User Id", 
#                                         tweet_filtered.columns[9]: "User Name", 
#                                         tweet_filtered.columns[10]: "User Location", 
#                                         tweet_filtered.columns[11]: "User Follower Count", 
#                                         tweet_filtered.columns[12]: "User Following Count", 
#                                         tweet_filtered.columns[13]: "User Likes Count", 
#                                         tweet_filtered.columns[14]: "User Tweets Count", 
#                                     })

# display(tweet_filtered)

In [11]:
# replies_data = tweet_filtered
# replies_data.to_csv('merge_catatanali07_retweets.csv', index=False)

# Bungs

## Raw Data

In [12]:
tweet = pd.read_csv("tweet_bungs_base.csv")
users = pd.read_csv("users_bungs_base.csv")
display(tweet)
display(users)

,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,https://twitter.com/__Bungs/status/15882389457...,2022-11-03 18:37:27+00:00,"Eh tokai , lo itu bahlul jadi kalo bikin opini...","Eh tokai , lo itu bahlul jadi kalo bikin opini...",1588238945791315970,"{'username': '__Bungs', 'id': 914271535, 'disp...",0,0,0,0,...,NaN,NaN,{'url': 'https://twitter.com/bachrum_achmadi/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://twitter.com/__Bungs/status/15882343673...,2022-11-03 18:19:15+00:00,Saya tetap beli rokok walaupun dianggap berbah...,Saya tetap beli rokok walaupun dianggap berbah...,1588234367335206914,"{'username': '__Bungs', 'id': 914271535, 'disp...",0,1,2,0,...,NaN,NaN,{'url': 'https://twitter.com/CNNIndonesia/stat...,NaN,NaN,"[{'username': 'DitjenPK', 'id': 3188251417, 'd...",NaN,NaN,NaN,NaN
2,https://twitter.com/__Bungs/status/15882327718...,2022-11-03 18:12:55+00:00,Otaknya dia kering bro ü§£ https://t.co/xQX22GRdBX,Otaknya dia kering bro ü§£ twitter.com/kangdede7...,1588232771863859200,"{'username': '__Bungs', 'id': 914271535, 'disp...",0,0,1,0,...,NaN,NaN,{'url': 'https://twitter.com/kangdede78/status...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://twitter.com/__Bungs/status/15882324703...,2022-11-03 18:11:43+00:00,"Berisik lo üò¥, modal oposisi itu cuma mainkan o...","Berisik lo üò¥, modal oposisi itu cuma mainkan o...",1588232470322851841,"{'username': '__Bungs', 'id': 914271535, 'disp...",0,0,3,0,...,NaN,NaN,{'url': 'https://twitter.com/BosPurwa/status/1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://twitter.com/__Bungs/status/15882314840...,2022-11-03 18:07:48+00:00,"Jangan sembunyikan bekas lukamu, itu yang memb...","Jangan sembunyikan bekas lukamu, itu yang memb...",1588231484069933057,"{'username': '__Bungs', 'id': 914271535, 'disp...",1,0,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30575,https://twitter.com/__Bungs/status/26496117619...,2012-11-04 05:24:01+00:00,Olly,Olly,264961176193097729,"{'username': '__Bungs', 'id': 914271535, 'disp...",0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30576,https://twitter.com/__Bungs/status/26488423224...,2012-11-04 00:18:16+00:00,Happy sunday,Happy sunday,264884232244047872,"{'username': '__Bungs', 'id': 914271535, 'disp...",0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30577,https://twitter.com/__Bungs/status/26421951539...,2012-11-02 04:16:56+00:00,http://t.co/qeZicwhQ,http://t.co/qeZicwhQ,264219515397738496,"{'username': '__Bungs', 'id': 914271535, 'disp...",0,0,0,0,...,[{'previewUrl': 'https://pbs.twimg.com/media/A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30578,https://twitter.com/__Bungs/status/26420201991...,2012-11-02 03:07:24+00:00,Prepare for RCTI program magician session 5 to...,Prepare for RCTI program magician session 5 to...,264202019919777793,"{'username': '__Bungs', 'id': 914271535, 'disp...",0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30579,https://twitter.com/__Bungs/status/26396103188...,2012-11-01 11:09:48+00:00,Blue is the colour,Blue is the colour,263961031880097792,"{'username': '__Bungs', 'id': 914271535, 'disp...",0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

          Id Username  Followers  Following  Tweets   Likes   Location
0  914271535  __Bungs       3781       1451  105401  459769  Indonesia

In [13]:
tweet_filtered = tweet.filter(items=["id", "date", "url", "content", "likeCount", "replyCount", "retweetCount", "retweetedTweet"])
tweet_filtered = tweet_filtered.assign(user_id=user2_data[0], user_name=user2_data[1], user_location=user2_data[2], 
                      follower_count=user2_data[3], following_count=user2_data[4], likes_count=user2_data[5], tweets_count=user2_data[6])
tweet_filtered = tweet_filtered.rename(columns={
                                        tweet_filtered.columns[0]: "Id", 
                                        tweet_filtered.columns[1]: "Tweet Time", 
                                        tweet_filtered.columns[2]: "Url", 
                                        tweet_filtered.columns[3]: "Tweet Text", 
                                        tweet_filtered.columns[4]: "Likes Count", 
                                        tweet_filtered.columns[5]: "Reply Count", 
                                        tweet_filtered.columns[6]: "Retweet Count", 
                                        tweet_filtered.columns[7]: "Retweeted Tweet", 
                                        tweet_filtered.columns[8]: "User Id", 
                                        tweet_filtered.columns[9]: "User Name", 
                                        tweet_filtered.columns[10]: "User Location", 
                                        tweet_filtered.columns[11]: "User Follower Count", 
                                        tweet_filtered.columns[12]: "User Following Count", 
                                        tweet_filtered.columns[13]: "User Likes Count", 
                                        tweet_filtered.columns[14]: "User Tweets Count", 
                                    })

display(tweet_filtered)

,Id,Tweet Time,Url,Tweet Text,Likes Count,Reply Count,Retweet Count,Retweeted Tweet,User Id,User Name,User Location,User Follower Count,User Following Count,User Likes Count,User Tweets Count
0,1588238945791315970,2022-11-03 18:37:27+00:00,https://twitter.com/__Bungs/status/15882389457...,"Eh tokai , lo itu bahlul jadi kalo bikin opini...",0,0,0,NaN,914271535,__Bungs,Indonesia,3788,1449,459936,105430
1,1588234367335206914,2022-11-03 18:19:15+00:00,https://twitter.com/__Bungs/status/15882343673...,Saya tetap beli rokok walaupun dianggap berbah...,2,0,1,NaN,914271535,__Bungs,Indonesia,3788,1449,459936,105430
2,1588232771863859200,2022-11-03 18:12:55+00:00,https://twitter.com/__Bungs/status/15882327718...,Otaknya dia kering bro ü§£ https://t.co/xQX22GRdBX,1,0,0,NaN,914271535,__Bungs,Indonesia,3788,1449,459936,105430
3,1588232470322851841,2022-11-03 18:11:43+00:00,https://twitter.com/__Bungs/status/15882324703...,"Berisik lo üò¥, modal oposisi itu cuma mainkan o...",3,0,0,NaN,914271535,__Bungs,Indonesia,3788,1449,459936,105430
4,1588231484069933057,2022-11-03 18:07:48+00:00,https://twitter.com/__Bungs/status/15882314840...,"Jangan sembunyikan bekas lukamu, itu yang memb...",3,1,0,NaN,914271535,__Bungs,Indonesia,3788,1449,459936,105430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30575,264961176193097729,2012-11-04 05:24:01+00:00,https://twitter.com/__Bungs/status/26496117619...,Olly,0,0,0,NaN,914271535,__Bungs,Indonesia,3788,1449,459936,105430
30576,264884232244047872,2012-11-04 00:18:16+00:00,https://twitter.com/__Bungs/status/26488423224...,Happy sunday,0,0,0,NaN,914271535,__Bungs,Indonesia,3788,1449,459936,105430
30577,264219515397738496,2012-11-02 04:16:56+00:00,https://twitter.com/__Bungs/status/26421951539...,http://t.co/qeZicwhQ,0,0,0,NaN,914271535,__Bungs,Indonesia,3788,1449,459936,105430
30578,264202019919777793,2012-11-02 03:07:24+00:00,https://twitter.com/__Bungs/status/26420201991...,Prepare for RCTI program magician session 5 to...,0,0,0,NaN,914271535,__Bungs,Indonesia,3788,1449,459936,105430
30579,263961031880097792,2012-11-01 11:09:48+00:00,https://twitter.com/__Bungs/status/26396103188...,Blue is the colour,0,0,0,NaN,914271535,__Bungs,Indonesia,3788,1449,459936,105430

In [14]:
base_data = tweet_filtered
base_data.to_csv('merge_bungs_base.csv', index=False)

## Replies Data

In [15]:
tweet = pd.read_csv("tweet_bungs_replies.csv")
users = pd.read_csv("users_bungs_replies.csv")
display(tweet)
display(users)

,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,https://twitter.com/Pr1nceOfWolves/status/1588...,2022-11-04 14:22:48+00:00,@__Bungs Agree,@__Bungs Agree,1588537250941644801,"{'username': 'Pr1nceOfWolves', 'id': 139297710...",0,0,2,0,...,NaN,NaN,NaN,1.588430e+18,"{'username': '__Bungs', 'id': 914271535, 'disp...","[{'username': '__Bungs', 'id': 914271535, 'dis...",NaN,NaN,NaN,NaN
1,https://twitter.com/Circle0fL1fe/status/158850...,2022-11-04 12:10:12+00:00,@__Bungs Exactly.,@__Bungs Exactly.,1588503878991237120,"{'username': 'Circle0fL1fe', 'id': 13885572636...",0,0,1,0,...,NaN,NaN,NaN,1.588430e+18,"{'username': '__Bungs', 'id': 914271535, 'disp...","[{'username': '__Bungs', 'id': 914271535, 'dis...",NaN,NaN,NaN,NaN
2,https://twitter.com/ir_turnip/status/158845087...,2022-11-04 08:39:35+00:00,"@__Bungs @KPK_RI Ini satu paket , ini bukan ke...","@__Bungs @KPK_RI Ini satu paket , ini bukan ke...",1588450877916217344,"{'username': 'ir_turnip', 'id': 15788792062047...",0,0,0,0,...,NaN,NaN,NaN,1.588116e+18,"{'username': '__Bungs', 'id': 914271535, 'disp...","[{'username': '__Bungs', 'id': 914271535, 'dis...",NaN,NaN,NaN,NaN
3,https://twitter.com/nuansabening28/status/1588...,2022-11-04 07:56:36+00:00,@__Bungs Order brp botol bung ü§©,@__Bungs Order brp botol bung ü§©,1588440058818088960,"{'username': 'nuansabening28', 'id': 949801697...",1,0,2,0,...,NaN,NaN,NaN,1.588437e+18,"{'username': '__Bungs', 'id': 914271535, 'disp...","[{'username': '__Bungs', 'id': 914271535, 'dis...",NaN,NaN,NaN,NaN
4,https://twitter.com/rm_wiyono2/status/15884143...,2022-11-04 06:14:21+00:00,@__Bungs @KPK_RI Perasaan formula e ini sepert...,@__Bungs @KPK_RI Perasaan formula e ini sepert...,1588414324803969024,"{'username': 'rm_wiyono2', 'id': 1449046642074...",0,0,0,0,...,NaN,NaN,NaN,1.588116e+18,"{'username': '__Bungs', 'id': 914271535, 'disp...","[{'username': '__Bungs', 'id': 914271535, 'dis...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37360,https://twitter.com/PrincessBrigita/status/265...,2012-11-07 02:11:00+00:00,"@TheLastFranky ya udin si pak aja dah,inget ye...","@TheLastFranky ya udin si pak aja dah,inget ye...",265999762682155008,"{'username': 'PrincessBrigita', 'id': 22391176...",1,0,0,0,...,NaN,NaN,NaN,2.659981e+17,"{'username': '__Bungs', 'id': 914271535, 'disp...",NaN,NaN,NaN,NaN,NaN
37361,https://twitter.com/PrincessBrigita/status/265...,2012-11-07 02:02:10+00:00,"@TheLastFranky ho oh,yg ga enak ksh kucing aje...","@TheLastFranky ho oh,yg ga enak ksh kucing aje...",265997541563322368,"{'username': 'PrincessBrigita', 'id': 22391176...",1,0,0,0,...,NaN,NaN,NaN,2.659961e+17,"{'username': '__Bungs', 'id': 914271535, 'disp...",NaN,NaN,NaN,NaN,NaN
37362,https://twitter.com/VRadioFM/status/2656835391...,2012-11-06 05:14:26+00:00,@TheLastFranky silahkan pilih lagu di #VoteThe...,@TheLastFranky silahkan pilih lagu di #VoteThe...,265683539150913536,"{'username': 'VRadioFM', 'id': 227607482, 'dis...",1,0,0,0,...,NaN,NaN,NaN,2.656806e+17,"{'username': '__Bungs', 'id': 914271535, 'disp...",NaN,"{'longitude': 106.807441, 'latitude': -6.180635}","{'fullName': 'Gambir, Indonesia', 'name': 'Gam...",['VoteTheSong'],NaN
37363,https://twitter.com/ekadeli/status/26543501598...,2012-11-05 12:46:54+00:00,@TheLastFranky masih..:),@TheLastFranky masih..:),265435015981191168,"{'username': 'ekadeli', 'id': 204800879, 'disp...",1,0,0,0,...,NaN,NaN,NaN,2.654343e+17,"{'username': '__Bungs', 'id': 914271535, 'disp...",NaN,NaN,NaN,NaN,NaN
37364,https://twitter.com/rockadocta/status/26543139...,2012-11-05 12:32:30+00:00,@TheLastFranky di sekitar senayan :-),@TheLastFranky di sekitar senayan :-),265431394132561920,"{'username': 'rockadocta', 'id': 78821538, 'di...",1,0,0,0,...,NaN,NaN,NaN,2.654309e+17,"{'username': '__Bungs', 'id': 914271535, 'disp...",NaN,NaN,NaN,NaN,NaN

,Id,Username,Followers,Following,Tweets,Likes,Location
0,1417137620186845191,dedek_1209,7295,3741,61473,27492,dimana ada üíô
1,1303615921550835712,RaniKancana__,59088,12916,303379,303263,Indonesia
2,202832527,jekjek1,642,849,33220,35957,NaN
3,1521109660949831680,SSobrah,1090,2134,2249,5108,NaN
4,1431943911749029891,amatbejo_,3190,3832,5026,16273,NaN
...,...,...,...,...,...,...,...
9293,250882114,fauzinuriman,4679,809,90998,74,Tanah Air
9294,146018074,r_djangkaru,354829,1621,65452,1266,Indonesia Raya
9295,227607482,VRadioFM,228644,2436,99147,4417,Jakarta
9296,73995743,IyankPo,1470,25,50158,30,"Jakarta, Indonesia"
9297,204800879,ekadeli,8298,158,4207,23,somewhere over the rainbow

In [16]:
tweet_filtered = tweet.filter(items=["id", "date", "url", "content", "likeCount", "replyCount", "retweetCount", "retweetedTweet"])

username_series = tweet.user.str.split("', '")
username_series = username_series.apply(lambda x: x[0].split("': '")[1])
tweet_filtered = tweet_filtered.assign(username_user=username_series)

tweet_filtered = tweet_filtered.merge(users, left_on="username_user", right_on="Username", how="left")
# tweet_filtered = tweet_filtered.assign(user_id=user1_data[0], user_name=user1_data[1], user_location=user1_data[2], 
#                       follower_count=user1_data[3], following_count=user1_data[4], likes_count=user1_data[5], tweets_count=user1_data[6])
tweet_filtered = tweet_filtered.drop('username_user', axis=1)
tweet_filtered = tweet_filtered.rename(columns={
                                        tweet_filtered.columns[0]: "Id", 
                                        tweet_filtered.columns[1]: "Tweet Time", 
                                        tweet_filtered.columns[2]: "Url", 
                                        tweet_filtered.columns[3]: "Tweet Text", 
                                        tweet_filtered.columns[4]: "Likes Count", 
                                        tweet_filtered.columns[5]: "Reply Count", 
                                        tweet_filtered.columns[6]: "Retweet Count", 
                                        tweet_filtered.columns[7]: "Retweeted Tweet", 
                                        tweet_filtered.columns[8]: "User Id", 
                                        tweet_filtered.columns[9]: "User Name", 
                                        tweet_filtered.columns[10]: "User Follower Count", 
                                        tweet_filtered.columns[11]: "User Following Count", 
                                        tweet_filtered.columns[12]: "User Tweets Count", 
                                        tweet_filtered.columns[13]: "User Likes Count", 
                                        tweet_filtered.columns[14]: "User Location", 
                                    })

display(tweet_filtered)

,Id,Tweet Time,Url,Tweet Text,Likes Count,Reply Count,Retweet Count,Retweeted Tweet,User Id,User Name,User Follower Count,User Following Count,User Tweets Count,User Likes Count,User Location
0,1588537250941644801,2022-11-04 14:22:48+00:00,https://twitter.com/Pr1nceOfWolves/status/1588...,@__Bungs Agree,2,0,0,NaN,1.392977e+18,Pr1nceOfWolves,4653.0,2486.0,3453.0,4139.0,in the night sky
1,1588503878991237120,2022-11-04 12:10:12+00:00,https://twitter.com/Circle0fL1fe/status/158850...,@__Bungs Exactly.,1,0,0,NaN,1.388557e+18,Circle0fL1fe,3375.0,3583.0,13844.0,17980.0,NaN
2,1588450877916217344,2022-11-04 08:39:35+00:00,https://twitter.com/ir_turnip/status/158845087...,"@__Bungs @KPK_RI Ini satu paket , ini bukan ke...",0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1588440058818088960,2022-11-04 07:56:36+00:00,https://twitter.com/nuansabening28/status/1588...,@__Bungs Order brp botol bung ü§©,2,1,0,NaN,9.498017e+17,nuansabening28,20443.0,14941.0,122825.0,59712.0,Indonesia
4,1588414324803969024,2022-11-04 06:14:21+00:00,https://twitter.com/rm_wiyono2/status/15884143...,@__Bungs @KPK_RI Perasaan formula e ini sepert...,0,0,0,NaN,1.449047e+18,rm_wiyono2,985.0,1122.0,6352.0,6122.0,indonesia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37360,265999762682155008,2012-11-07 02:11:00+00:00,https://twitter.com/PrincessBrigita/status/265...,"@TheLastFranky ya udin si pak aja dah,inget ye...",0,1,0,NaN,2.239118e+08,PrincessBrigita,9025.0,1545.0,92657.0,429.0,Jakarta - Bekasi
37361,265997541563322368,2012-11-07 02:02:10+00:00,https://twitter.com/PrincessBrigita/status/265...,"@TheLastFranky ho oh,yg ga enak ksh kucing aje...",0,1,0,NaN,2.239118e+08,PrincessBrigita,9025.0,1545.0,92657.0,429.0,Jakarta - Bekasi
37362,265683539150913536,2012-11-06 05:14:26+00:00,https://twitter.com/VRadioFM/status/2656835391...,@TheLastFranky silahkan pilih lagu di #VoteThe...,0,1,0,NaN,2.276075e+08,VRadioFM,228644.0,2436.0,99147.0,4417.0,Jakarta
37363,265435015981191168,2012-11-05 12:46:54+00:00,https://twitter.com/ekadeli/status/26543501598...,@TheLastFranky masih..:),0,1,0,NaN,2.048009e+08,ekadeli,8298.0,158.0,4207.0,23.0,somewhere over the rainbow
37364,265431394132561920,2012-11-05 12:32:30+00:00,https://twitter.com/rockadocta/status/26543139...,@TheLastFranky di sekitar senayan :-),0,1,0,NaN,7.882154e+07,rockadocta,7782.0,1049.0,203943.0,960.0,NaN

In [17]:
replies_data = tweet_filtered
replies_data.to_csv('merge_bungs_replies.csv', index=False)

## Retweet Data

In [18]:
tweet = pd.read_csv("tweet_bungs_retweets.csv")
users = pd.read_csv("users_bungs_retweets.csv")
display(tweet)
display(users)

,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,https://twitter.com/gedhanggg/status/158830189...,2022-11-03 22:47:36+00:00,RT @memorysongs2022: @__Bungs @KPK_RI https://...,RT @memorysongs2022: @__Bungs @KPK_RI https://...,1588301898284929025,"{'username': 'gedhanggg', 'id': 12799995383846...",0,2,0,0,...,[{'previewUrl': 'https://pbs.twimg.com/media/F...,{'url': 'https://twitter.com/memorysongs2022/s...,NaN,NaN,NaN,"[{'username': 'memorysongs2022', 'id': 2294373...",NaN,NaN,NaN,NaN
1,https://twitter.com/Sangpisanggg1/status/15881...,2022-11-03 13:23:09+00:00,RT @memorysongs2022: @__Bungs @KPK_RI https://...,RT @memorysongs2022: @__Bungs @KPK_RI https://...,1588159849543929856,"{'username': 'Sangpisanggg1', 'id': 1279989517...",0,2,0,0,...,[{'previewUrl': 'https://pbs.twimg.com/media/F...,{'url': 'https://twitter.com/memorysongs2022/s...,NaN,NaN,NaN,"[{'username': 'memorysongs2022', 'id': 2294373...",NaN,NaN,NaN,NaN
2,https://twitter.com/bishidielmomeg1/status/158...,2022-11-01 05:27:17+00:00,RT @AgungSu76387898: @__Bungs https://t.co/KfB...,RT @AgungSu76387898: @__Bungs https://t.co/KfB...,1587315320280084480,"{'username': 'bishidielmomeg1', 'id': 15405196...",0,3,0,0,...,[{'previewUrl': 'https://pbs.twimg.com/media/F...,{'url': 'https://twitter.com/AgungSu76387898/s...,NaN,NaN,NaN,"[{'username': 'AgungSu76387898', 'id': 1479719...",NaN,NaN,NaN,NaN
3,https://twitter.com/markus_joe/status/15870862...,2022-10-31 14:17:05+00:00,RT @AgungSu76387898: @__Bungs https://t.co/KfB...,RT @AgungSu76387898: @__Bungs https://t.co/KfB...,1587086257980469248,"{'username': 'markus_joe', 'id': 236309833, 'd...",0,3,0,0,...,[{'previewUrl': 'https://pbs.twimg.com/media/F...,{'url': 'https://twitter.com/AgungSu76387898/s...,NaN,NaN,NaN,"[{'username': 'AgungSu76387898', 'id': 1479719...",NaN,NaN,NaN,NaN
4,https://twitter.com/DwiNoviantoro1/status/1586...,2022-10-30 18:50:42+00:00,RT @AgungSu76387898: @__Bungs https://t.co/KfB...,RT @AgungSu76387898: @__Bungs https://t.co/KfB...,1586792731191693312,"{'username': 'DwiNoviantoro1', 'id': 118045996...",0,3,0,0,...,[{'previewUrl': 'https://pbs.twimg.com/media/F...,{'url': 'https://twitter.com/AgungSu76387898/s...,NaN,NaN,NaN,"[{'username': 'AgungSu76387898', 'id': 1479719...",NaN,NaN,NaN,NaN

,Id,Username,Followers,Following,Tweets,Likes,Location
0,1279999538384666624,gedhanggg,451,642,6270,9990,NaN
1,1279989517483532290,Sangpisanggg1,585,796,6410,10651,NaN
2,1540519651506941952,bishidielmomeg1,139,756,2043,4653,NaN
3,236309833,markus_joe,70,93,5252,8241,NaN
4,1180459966299131906,DwiNoviantoro1,1966,2127,51937,65782,NaN

In [19]:
tweet_filtered = tweet.filter(items=["id", "date", "url", "content", "likeCount", "replyCount", "retweetCount", "retweetedTweet"])

username_series = tweet.user.str.split("', '")
username_series = username_series.apply(lambda x: x[0].split("': '")[1])
tweet_filtered = tweet_filtered.assign(username_user=username_series)

tweet_filtered = tweet_filtered.merge(users, left_on="username_user", right_on="Username", how="left")
# tweet_filtered = tweet_filtered.assign(user_id=user1_data[0], user_name=user1_data[1], user_location=user1_data[2], 
#                       follower_count=user1_data[3], following_count=user1_data[4], likes_count=user1_data[5], tweets_count=user1_data[6])
tweet_filtered = tweet_filtered.drop('username_user', axis=1)
tweet_filtered = tweet_filtered.rename(columns={
                                        tweet_filtered.columns[0]: "Id", 
                                        tweet_filtered.columns[1]: "Tweet Time", 
                                        tweet_filtered.columns[2]: "Url", 
                                        tweet_filtered.columns[3]: "Tweet Text", 
                                        tweet_filtered.columns[4]: "Likes Count", 
                                        tweet_filtered.columns[5]: "Reply Count", 
                                        tweet_filtered.columns[6]: "Retweet Count", 
                                        tweet_filtered.columns[7]: "Retweeted Tweet", 
                                        tweet_filtered.columns[8]: "User Id", 
                                        tweet_filtered.columns[9]: "User Name", 
                                        tweet_filtered.columns[10]: "User Follower Count", 
                                        tweet_filtered.columns[11]: "User Following Count", 
                                        tweet_filtered.columns[12]: "User Tweets Count", 
                                        tweet_filtered.columns[13]: "User Likes Count", 
                                        tweet_filtered.columns[14]: "User Location", 
                                    })

display(tweet_filtered)

,Id,Tweet Time,Url,Tweet Text,Likes Count,Reply Count,Retweet Count,Retweeted Tweet,User Id,User Name,User Follower Count,User Following Count,User Tweets Count,User Likes Count,User Location
0,1588301898284929025,2022-11-03 22:47:36+00:00,https://twitter.com/gedhanggg/status/158830189...,RT @memorysongs2022: @__Bungs @KPK_RI https://...,0,0,2,{'url': 'https://twitter.com/memorysongs2022/s...,1279999538384666624,gedhanggg,451,642,6270,9990,NaN
1,1588159849543929856,2022-11-03 13:23:09+00:00,https://twitter.com/Sangpisanggg1/status/15881...,RT @memorysongs2022: @__Bungs @KPK_RI https://...,0,0,2,{'url': 'https://twitter.com/memorysongs2022/s...,1279989517483532290,Sangpisanggg1,585,796,6410,10651,NaN
2,1587315320280084480,2022-11-01 05:27:17+00:00,https://twitter.com/bishidielmomeg1/status/158...,RT @AgungSu76387898: @__Bungs https://t.co/KfB...,0,0,3,{'url': 'https://twitter.com/AgungSu76387898/s...,1540519651506941952,bishidielmomeg1,139,756,2043,4653,NaN
3,1587086257980469248,2022-10-31 14:17:05+00:00,https://twitter.com/markus_joe/status/15870862...,RT @AgungSu76387898: @__Bungs https://t.co/KfB...,0,0,3,{'url': 'https://twitter.com/AgungSu76387898/s...,236309833,markus_joe,70,93,5252,8241,NaN
4,1586792731191693312,2022-10-30 18:50:42+00:00,https://twitter.com/DwiNoviantoro1/status/1586...,RT @AgungSu76387898: @__Bungs https://t.co/KfB...,0,0,3,{'url': 'https://twitter.com/AgungSu76387898/s...,1180459966299131906,DwiNoviantoro1,1966,2127,51937,65782,NaN

In [20]:
replies_data = tweet_filtered
replies_data.to_csv('merge_bungs_retweets.csv', index=False)

# Merge per User

In [33]:
# merging two csv files
user1_df = pd.concat(map(pd.read_csv, ['merge_catatanali07_base.csv', 'merge_catatanali07_replies.csv']), ignore_index=True)
user1_df['Tweet Time'] = pd.to_datetime(user1_df['Tweet Time'])
print(type(user1_df['Tweet Time'][0]))
user1_df.sort_values(by='Tweet Time', inplace=True)
user1_df.reset_index(inplace=True)
user1_df.to_csv('catatanali07.csv')

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [35]:
# merging two csv files
user2_df = pd.concat(map(pd.read_csv, ['merge_bungs_base.csv', 'merge_bungs_replies.csv', 'merge_bungs_retweets.csv']), ignore_index=True)
user2_df['Tweet Time'] = pd.to_datetime(user2_df['Tweet Time'])
print(type(user2_df['Tweet Time'][0]))
user2_df.sort_values(by='Tweet Time', inplace=True)
user2_df.reset_index(inplace=True)
user2_df.to_csv('__bungs.csv')

<class 'pandas._libs.tslibs.timestamps.Timestamp'>